name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Amadevus/pwsh-script@v2.0.1
      with:
        script: |
          $moduleDirectoryPath = Join-Path $github.workspace "sandersaares.devops-scripts"
          $moduleFilePath = Join-Path $moduleDirectoryPath "sandersaares.devops-scripts.psd1"

          $timestamp = [DateTimeOffset]::UtcNow.ToString("yyMMddHHmmss")

          Import-Module $moduleFilePath
          Set-PowerShellModuleMetadataBeforeBuild -path $moduleFilePath -buildTimestamp $timestamp
          Set-PowerShellModuleBuildString -path $moduleFilePath -buildTimestamp $timestamp
          Publish-Module -Path "$moduleDirectoryPath" -NugetAPIKey "${{ secrets.PSGALLERY_API_KEY }}" -Verbose
    - uses: actions/upload-artifact@v2
      with:
        name: Scripts
        path: sandersaares.devops-scripts/*.ps1