name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - id: publish_module
      uses: Amadevus/pwsh-script@v2.0.1
      with:
        script: |
          $moduleDirectoryPath = Join-Path $github.workspace "sandersaares.devops-scripts"
          $moduleFilePath = Join-Path $moduleDirectoryPath "sandersaares.devops-scripts.psd1"

          $timestamp = [DateTimeOffset]::UtcNow.ToString("yyMMddHHmmss")

          Import-Module $moduleFilePath
          # Outputs versionstring variable.
          Set-PowerShellModuleMetadataBeforeBuild -path $moduleFilePath -buildTimestamp $timestamp
          Set-PowerShellModuleBuildString -path $moduleFilePath -buildTimestamp $timestamp
          Publish-Module -Path "$moduleDirectoryPath" -NugetAPIKey "${{ secrets.PSGALLERY_API_KEY }}" -Verbose
    - uses: papeloto/action-zip@v1
      with:
        files: sandersaares.devops-scripts/*.ps1
        dest: Scripts.zip
    - uses: marvinpinto/action-automatic-releases@latest
      env:
        versionstring: ${{ steps.publish_module.outputs.versionstring }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        title: ${{ steps.publish_module.outputs.versionstring }}
        files: |
          Scripts.zip